### ISSUE TITLE
Client Upgrade section discusses Major Release Upgrades only

### ISSUE THREAD

**Issue by thallma** [uyuni-project/uyuni-docs#593] opened 2020-10-07 07:34 UTC
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/upgrade/client-intro.html just describes Major Release Upgrades. It seems there is no SP Migration anywhere described in detail. Just the highlight description that then links to Major Release Upgrade process.

**Comment by Loquacity** [comment] 2020-10-08 00:18
Duplicate of https://github.com/uyuni-project/uyuni-docs/issues/592

**Closed by Loquacity** 2020-10-08 00:18 UTC
