### ISSUE TITLE
SUMA 4.3 docs have the wrong module release version

### ISSUE THREAD

**Issue by slsnow** [uyuni-project/uyuni-docs#2733] opened 2024-01-26 10:24 UTC
## Documentation Update Required

Incorrect version release version number in instructions

## What does the documentation say now?

https://documentation.suse.com/suma/4.3/en/suse-manager/installation-and-upgrade/pubcloud-setup.html#_activate_the_public_cloud_module

```
SUSEConnect -p sle-module-public-cloud/15.5/x86_64
```

## What change is required?

Should say 
```
SUSEConnect -p sle-module-public-cloud/15.4/x86_64
```

Also of note, in the public cloud now you can use an SCC registration code, but still use the registercloudguest infrastructure (yes for BYOS), like this:

```
registercloudguest -r YOUR_CODE
```
More details: https://documentation.suse.com/sle-public-cloud/all/html/public-cloud/cha-admin.html#sec-admin-register

Assuming you use an appropriate SUMA code, and you're using the SUMA image, everything you need should get activated. Using this, instead of going directly to the SCC, potentially has advantages. You should still verify that everything is activated before moving on.

SUSEConnect --status-text and everything still work after you've done the registercloudguest.

## Version

SUMA 4.3 docs. SUMA 4.3 is still on SLES 15 SP4, and hasn't moved to 15 SP5.

**Comment by keichwa** [comment] 2024-02-07 07:22
Thanks for the report!

**Comment by cwickert** [comment] 2024-03-05 15:47
This looks like a duplicate of #2700 

@keichwa, what is the status here? Should be trivial to fix.

**Comment by keichwa** [comment] 2024-03-06 16:22
> This looks like a duplicate of #2700
> 
> @keichwa, what is the status here? Should be trivial to fix.

Probably.  Now I try this one: https://github.com/uyuni-project/uyuni-docs/pull/2841

**Closed** 2024-03-07 09:21 UTC
Labels: docs backlog, manager-4.3
