### ISSUE TITLE
amazonlinux 2 channels not defined? 

### ISSUE THREAD

**Issue by eins** [uyuni-project/uyuni-docs#999] opened 2021-06-18 14:39 UTC
## How to add amazonlinux 2 channels in Uyuni release 2021.05

I tried to add amazonlinux 2 channels from this link
[uyuni-clients-amazon.html](https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-amazon.html)

For some reason the Table 1 Amazon Linux Channels - cli doesn't have a
clear example.

the Procedure part has channles_label but I didn't know how to replace
it with amazonlinux2 channels

this didn't work for me:
```
spacewalk-common-channels -a  amazonlinux2-core amazonlinux2-uyuni-client
SUSE Manager username: beispiel01
SUSE Manager password:
No channels matching your selection.
```
after try and error I ran this and works:
```
spacewalk-common-channels \
amazonlinux2-uyuni-client \
amazonlinux2-core
SUSE Manager username: beispiel01
SUSE Manager password:
```

after this I tried to run spacewalk-repo-sync but I forgot to save the error. it said something like you need to add a channel.
```
# this didn't work. 
# a few months ago when I added ubuntu channels I only used spacewalk-repo-sync alone.
spacewalk-repo-sync --channel amazonlinux2-core
```

Because of this I went to the uyuni url and sync both channels manually.
then I checked the logs and the sync started

```
tail -f /var/log/rhn/reposync/amazonlinux2-core-aarch64.log 
tail -f /var/log/rhn/reposync/amazonlinux2-uyuni-client-x86_64.log 
tail -f /var/log/rhn/reposync/amazonlinux2-core-x86_64.log 
```

What is the right way to add a channel now ?
can we add the -a in the html file too ?

links that I checked: 
+ https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-amazon.html
+ https://raw.githubusercontent.com/uyuni-project/uyuni-docs/uyuni-2021.05/modules/client-configuration/pages/clients-amazon.adoc
+ https://github.com/uyuni-project/uyuni-docs/blob/uyuni-2021.05/modules/client-configuration/pages/clients-amazon.adoc

![uyuniDocs-amazonlinuxV2-Fehler01](https://user-images.githubusercontent.com/5210927/122577793-92333c80-d029-11eb-899b-6e0f19711548.png)

## Version
```
zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2020.09-98.2.uyuni installed)
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by juliogonzalez** [comment] 2021-06-18 14:47
@eins this looks to me as almost a duplicate of #3893 but with more information. But it's not a problem for the docs.I will close the bug here.

As I told at the other bug:

> Will Amazon Linux for aarch64 work fine? It should, but we don't know. And that's why we did not document it. Please give it a try and let us know :-)

The docs will not have `aarch64` documented until it's tested. And of course, you can help us with that.

```
spacewalk-common-channels -a  amazonlinux2-core amazonlinux2-uyuni-client
```

You didn't specify what architecture you want. You need to use `-a` with an value.

And:
```
spacewalk-repo-sync --channel amazonlinux2-core
```

I am pretty sure the error was "the channel does not exist, see if you need to add it".

And the reason is what I told at the other bug:

> You are mentioning and error, but didn't provide the actual error, so all I can think of is that you specified the wrong channel label. The channel label includes the architecture. Check the list (IIRC you can pass an argument to `spacewalk-repo-sync`.

So in both cases, you need to specify the architecture, for adding the channels, and for syncing them after they are added.

**Closed by juliogonzalez** 2021-06-18 14:47 UTC

**Comment by eins** [comment] 2021-06-18 17:19
@juliogonzalez 
I ran this line 
```
spacewalk-common-channels -a  amazonlinux2-core amazonlinux2-uyuni-client
No channels matching your selection.
```

I can't bootstrap an ARM64 amazonlinuxv2 minion.
I had this error in the uyuni url

```
file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf

```

I have arm64 repositories but something is wrong
```
mgr-create-bootstrap-repo -l
1. amazonlinux-2-aarch64-uyuni
2. amazonlinux-2-x86_64-uyuni
3. openSUSE-Leap-15.2-x86_64-uyuni
```
Shirocco88 told me in gitter to add  /var/log/rhn/rhn_web_ui.log output

```
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:189)
        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462)
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:138)
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:152)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1254)
        at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:741)
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:694)
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:684)
        at org.apache.coyote.ajp.AjpProcessor.writeData(AjpProcessor.java:1260)
        at org.apache.coyote.ajp.AjpProcessor.access$600(AjpProcessor.java:58)
        at org.apache.coyote.ajp.AjpProcessor$SocketOutputBuffer.doWrite(AjpProcessor.java:1332)
        at org.apache.coyote.Response.doWrite(Response.java:601)
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:339)
        ... 52 more
2021-06-18 15:38:12,250 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-25] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
2021-06-18 15:40:43,797 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-20] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
2021-06-18 16:36:52,992 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-30] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
2021-06-18 17:16:20,376 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-22] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): Parent directory not present
service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion.d/susemanager.conf
~                                                                                                                                           
```
